version: '3.8'
services:
  #======================================================
  # App
  #======================================================
  app:
    container_name: app
    image: riconet/apache:8.1
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  #======================================================
  # Database
  #======================================================
  db:
    container_name: db
    image: mariadb:10.3.37
    command: mysqld --character-set-server=utf8
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:delegated
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=shopware
  #======================================================
  # Adminer
  #======================================================
  adminer:
    image: adminer:latest
    links:
      - db
    restart: always
    ports:
      - 8080:8080
  #======================================================
  # Mailhog
  #======================================================
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
#======================================================
# Volumes
#======================================================
volumes:
  db-data:
