name: Astro Deploy (Manual)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install and build
        uses: withastro/action@v0
        with:
          path: astro/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: astro/dist
          remote_path: kunden/homepages/2/d964308919/htdocs/astro
          remote_host: access964308919.webspace-data.io
          remote_user: u112422749$
          remote_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

